### ISSUE TITLE
moveLeft and selectLeft on CONSTANTS_LIKE_THIS puts the cursor in a weird spot

### ISSUE THREAD

**Issue by drew-wallace** [mlewand/vscode-select-part-of-word#24]
Steps to reproduce:

`HAVE_A_CONSTANT_LIKE_THIS| <--Cursor`

moveLeft command:

`HAVE_A_CONSTANT_LIKE_|THIS`

moveLeft command:

`HAVE_A_CONSTANT_LIK|E_THIS`

Notice it's now in the middle, more specifically, one character away from the `_`. The result should have been:

`HAVE_A_CONSTANT_|LIKE_THIS`

**Comment by mlewand** [comment]
Thanks for the report, I can reproduce it and it's definitely a bug. I'll take a look at this in couple of days. Cheers!

**Comment by mlewand** [comment]
Actually I was  able to close it right off the bat. 🙂
